import {findTaxonomyValue} from "./taxonomiesHelper.js";
let _ = require('lodash');

const colors = [
  {name: 'hds-alert', rgb: '#ffda07'  },
  {name: 'hds-alert-light', rgb: '#fff4b4'  },
  {name: 'hds-alert-dark', rgb: '#d18200'  },
  {name: 'hds-black', rgb: '#000'  },
  {name: 'hds-black-05', rgb: '#f1f1f1'  },
  {name: 'hds-black-10', rgb: '#e5e5e5'  },
  {name: 'hds-black-20', rgb: '#ccc'  },
  {name: 'hds-black-30', rgb: '#b2b2b2'  },
  {name: 'hds-black-40', rgb: '#999999'  },
  {name: 'hds-black-50', rgb: 'grey'  },
  {name: 'hds-black-60', rgb: '#666'  },
  {name: 'hds-black-70', rgb: '#4c4c4c'  },
  {name: 'hds-black-80', rgb: '#333'  },
  {name: 'hds-black-90', rgb: '#1a1a1a'  },
  {name: 'hds-brick', rgb: '#b2719'  },
  {name: 'hds-brick-light', rgb: '#ffeeed' },
  {name: 'hds-brick-medium-light', rgb: '#facbc8' },
  {name: 'hds-brick-dark', rgb: '#800eo4' },
  {name: 'hds-bus', rgb: '#000bf'  },
  {name: 'hds-bus-light', rgb: '#f0f0ff'  },
  {name: 'hds-bus-medium-light', rgb: '#ccf'  },
  {name: 'hds-bus-dark', rgb: '#00005e'  },
  {name: 'hds-coat-of-arms', rgb: '#0072c6'  },
  {name: 'hds-coat-of-arms-light', rgb: '#e6f4ff'  },
  {name: 'hds-coat-of-arms-medium-light', rgb: '#b5daf7'  },
  {name: 'hds-coat-of-arms-dark', rgb: '#005799'  },
  {name: 'hds-copper', rgb: '#00d7a7'  },
  {name: 'hds-copper-light', rgb: '#cffaf1'  },
  {name: 'hds-copper-medium-light', rgb: '#9ef0de'  },
  {name: 'hds-copper-dark', rgb: '#00a17d'  },
  {name: 'hds-engel', rgb: '#ffe977'  },
  {name: 'hds-engel-light', rgb: '#fff9fb'  },
  {name: 'hds-engel-medium-light', rgb: '#fff3b8'  },
  {name: 'hds-engel-dark', rgb: '#dbc030'  },
  {name: 'hds-fog', rgb: '#9fc9eb'  },
  {name: 'hds-fog-light', rgb: '#e8f3fc'  },
  {name: 'hds-fog-medium-light', rgb: '#d0e6f7'  },
  {name: 'hds-fog-dark', rgb: '#72a5cf'  },
  {name: 'hds-gold', rgb: '#c2a251'  },
  {name: 'hds-gold-light', rgb: '#f7f2e4'  },
  {name: 'hds-gold-medium-light', rgb: '#e8d7a7'  },
  {name: 'hds-gold-dark', rgb: '#9e823c'  },
  {name: 'hds-metro', rgb: '#fd4f00'  },
  {name: 'hds-metro-light', rgb: '#ffeee6'  },
  {name: 'hds-metro-medium-light', rgb: '#ffcab3'  },
  {name: 'hds-metro-dark', rgb: '#bd2f00'  },
  {name: 'hds-silver', rgb: '#dedfe1'  },
  {name: 'hds-silver-light', rgb: '#f7f7f8'  },
  {name: 'hds-silver-medium-light', rgb: '#efeff0'  },
  {name: 'hds-silver-dark', rgb: '#b0b8bf'  },
  {name: 'hds-summer', rgb: '#ffc61e'  },
  {name: 'hds-summer-light', rgb: '#fff4dd4'  },
  {name: 'hds-summer-medium-light', rgb: '#ffe49c'  },
  {name: 'hds-summer-dark', rgb: '#cc9200'  },
  {name: 'hds-suomenlinna', rgb: '#f5a3c7'  },
  {name: 'hds-suomenlinna-light', rgb: '#fff4d4'  },
  {name: 'hds-suomenlinna-medium-light', rgb: '#ffdbeb'  },
  {name: 'hds-suomenlinna-dark', rgb: '#e673a5'  },
  {name: 'hds-tram', rgb: '#009246'  },
  {name: 'hds-tram-light', rgb: '#dff0f7'  },
  {name: 'hds-tram-medium-light', rgb: '#a3e3c2'  },
  {name: 'hds-tram-dark', rgb: '#006631'  },
  {name: 'hds-error', rgb: '#b01038'  },
  {name: 'hds-error-light', rgb: '#f632e6'  },
  {name: 'hds-error-dark', rgb: '#8d0d2d'  },
  {name: 'hds-info', rgb: '#0062b9'  },
  {name: 'hds-info-light', rgb: '#e5eff8'  },
  {name: 'hds-info-dark', rgb: '#004f94'  },
  {name: 'hds-success', rgb: '#007a64'  },
  {name: 'hds-success-light', rgb: '#e2f5f3'  },
  {name: 'hds-success-dark', rgb: '#006250'  },
  {name: 'typa-blue', rgb: 'blue'},
];

export const getColor = (id, taxonomies) => {
  const name = findTaxonomyValue(id, taxonomies);
  const c = _.find(colors, {name: name}).rgb;
  if (!c) {
    console.log('undefined color ' + id + ' ' + name);
  }
  return c;
}
